#nullable enable
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Commandor.Generators;

[Generator]
public class CommandHandlerGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new CommandHandlerSyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxReceiver is not CommandHandlerSyntaxReceiver receiver)
            return;

        foreach (var interfaceDecl in receiver.CandidateInterfaces)
        {
            var model = context.Compilation.GetSemanticModel(interfaceDecl.SyntaxTree);
            var interfaceSymbol = model.GetDeclaredSymbol(interfaceDecl) as INamedTypeSymbol;

            if (interfaceSymbol == null)
                continue;

            var handlerMethods = GetHandlerMethods(interfaceSymbol, context.Compilation);
            if (!handlerMethods.Any())
                continue;

            var source = GenerateHandlers(interfaceSymbol, handlerMethods, context.Compilation);
            if (string.IsNullOrEmpty(source))
                continue;

            var fileName = $"{interfaceSymbol.ToDisplayString().Replace(".", "_").Replace("<", "_").Replace(">", "_")}_Handlers.g.cs";
            context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
        }
    }

    private static List<IMethodSymbol> GetHandlerMethods(INamedTypeSymbol interfaceSymbol, Compilation compilation)
    {
        var handlerMethods = new List<IMethodSymbol>();

        var commandHandlerAttribute = compilation.GetTypeByMetadataName("Commandor.CommandHandlerAttribute");
        var queryHandlerAttribute = compilation.GetTypeByMetadataName("Commandor.QueryHandlerAttribute");

        if (commandHandlerAttribute == null && queryHandlerAttribute == null)
            return handlerMethods;

        foreach (var member in interfaceSymbol.GetMembers().OfType<IMethodSymbol>())
        {
            if (member.GetAttributes().Any(attr =>
                    SymbolEqualityComparer.Default.Equals(attr.AttributeClass, commandHandlerAttribute) ||
                    SymbolEqualityComparer.Default.Equals(attr.AttributeClass, queryHandlerAttribute)))
            {
                handlerMethods.Add(member);
            }
        }

        return handlerMethods;
    }

    private static string GenerateHandlers(INamedTypeSymbol interfaceSymbol, List<IMethodSymbol> handlerMethods, Compilation compilation)
    {
        var sb = new StringBuilder();
        var namespaceName = interfaceSymbol.ContainingNamespace.ToDisplayString();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");

        foreach (var method in handlerMethods)
        {
            var handlerSource = GenerateHandler(interfaceSymbol, method, compilation);
            if (!string.IsNullOrEmpty(handlerSource))
                sb.AppendLine(handlerSource);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateHandler(INamedTypeSymbol interfaceSymbol, IMethodSymbol method, Compilation compilation)
    {
        if (method.Parameters.Length == 0)
            return string.Empty;

        var requestParameter = method.Parameters[0];
        var requestType = requestParameter.Type;
        var returnType = method.ReturnType;

        if (returnType is not INamedTypeSymbol namedReturnType || namedReturnType.Name != "Task")
            return string.Empty;

        var responseType = namedReturnType.TypeArguments.Length > 0 ? namedReturnType.TypeArguments[0] : null;

        var queryAttribute = compilation.GetTypeByMetadataName("Commandor.QueryHandlerAttribute");

        var isQueryHandler = queryAttribute != null && method.GetAttributes()
            .Any(attr => SymbolEqualityComparer.Default.Equals(attr.AttributeClass, queryAttribute));

        var format = new SymbolDisplayFormat(
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            miscellaneousOptions: SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier,
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included);

        var requestTypeName = requestType.ToDisplayString(format);
        var responseTypeName = responseType?.ToDisplayString(format);
        var interfaceTypeName = interfaceSymbol.ToDisplayString(format);

        var sb = new StringBuilder();
        var servicePrefix = interfaceSymbol.Name.TrimStart('I');
        var handlerName = $"{servicePrefix}{method.Name}Handler";

        if (responseType != null)
        {
            sb.AppendLine($"    internal sealed class {handlerName} : global::Commandor.IRequestHandler<{requestTypeName}, {responseTypeName}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        private readonly {interfaceTypeName} _service;");
            if (isQueryHandler)
            {
                sb.AppendLine("        private readonly global::Microsoft.Extensions.Caching.Memory.IMemoryCache _cache;");
                sb.AppendLine("        private readonly global::Commandor.CommandorContext _context;");
            }
            sb.AppendLine();
            
            var constructorArgs = isQueryHandler 
                ? $"{interfaceTypeName} service, global::Microsoft.Extensions.Caching.Memory.IMemoryCache cache, global::Commandor.CommandorContext context"
                : $"{interfaceTypeName} service";

            sb.AppendLine($"        public {handlerName}({constructorArgs})");
            sb.AppendLine("        {");
            sb.AppendLine("            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));");
            if (isQueryHandler)
            {
                sb.AppendLine("            _cache = cache ?? throw new global::System.ArgumentNullException(nameof(cache));");
                sb.AppendLine("            _context = context ?? throw new global::System.ArgumentNullException(nameof(context));");
            }
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        public async global::System.Threading.Tasks.Task<{responseTypeName}> HandleAsync({requestTypeName} request, global::System.Threading.CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            if (isQueryHandler)
            {
                sb.AppendLine($"            var cacheKey = global::Commandor.CacheKeyBuilder.Build(typeof({interfaceTypeName}), \"{method.Name}\", request);");
                var patternType = responseTypeName?.TrimEnd('?') ?? responseTypeName;
                sb.AppendLine($"            if (global::Microsoft.Extensions.Caching.Memory.CacheExtensions.TryGetValue(_cache, cacheKey, out object? cachedObj) && cachedObj is {patternType} cachedValue)");
                sb.AppendLine("            {");
                sb.AppendLine("                return cachedValue;");
                sb.AppendLine("            }");
                sb.AppendLine();
                sb.AppendLine($"            var result = await _service.{method.Name}(request, cancellationToken).ConfigureAwait(false);");
                sb.AppendLine();
                sb.AppendLine("            var options = new global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions();");
                sb.AppendLine($"            global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryExtensions.AddExpirationToken(options, _context.GetToken(typeof({interfaceTypeName})));");
                sb.AppendLine("            global::Microsoft.Extensions.Caching.Memory.CacheExtensions.Set(_cache, cacheKey, result, options);");
                sb.AppendLine();
                sb.AppendLine("            return result;");
            }
            else
            {
                sb.AppendLine($"            return await _service.{method.Name}(request, cancellationToken).ConfigureAwait(false);");
            }
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine($"    internal sealed class {handlerName} : global::Commandor.IRequestHandler<{requestTypeName}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        private readonly {interfaceTypeName} _service;");
            sb.AppendLine();
            sb.AppendLine($"        public {handlerName}({interfaceTypeName} service)");
            sb.AppendLine("        {");
            sb.AppendLine("            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        public async global::System.Threading.Tasks.Task HandleAsync({requestTypeName} request, global::System.Threading.CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine($"            await _service.{method.Name}(request, cancellationToken).ConfigureAwait(false);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        sb.AppendLine();
        return sb.ToString();
    }
}

internal sealed class CommandHandlerSyntaxReceiver : ISyntaxReceiver
{
    public List<InterfaceDeclarationSyntax> CandidateInterfaces { get; } = new();

    public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
    {
        if (syntaxNode is not InterfaceDeclarationSyntax interfaceDecl)
            return;

        foreach (var member in interfaceDecl.Members)
        {
            if (member is MethodDeclarationSyntax methodDecl && methodDecl.AttributeLists.Count > 0)
            {
                CandidateInterfaces.Add(interfaceDecl);
                break;
            }
        }
    }
}
