#nullable enable
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Commandor.Generators;

/// <summary>
/// Incremental source generator for Commandor handler classes.
/// Upgrades from the legacy ISourceGenerator API to IIncrementalGenerator so the
/// generator only re-runs when the affected interface syntax actually changes,
/// giving faster IDE feedback and incremental build performance.
/// </summary>
[Generator(LanguageNames.CSharp)]
public class CommandHandlerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Predicate: cheap structural check — any interface with a method carrying
        // CommandHandler or QueryHandler attributes.  No semantic model yet.
        var interfaceProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsInterfaceWithHandlerAttributes(node),
                transform: static (ctx, ct) =>
                    ctx.SemanticModel.GetDeclaredSymbol((InterfaceDeclarationSyntax)ctx.Node, ct) as INamedTypeSymbol)
            .Where(static sym => sym is not null)
            .Select(static (sym, _) => sym!);

        // Pair each interface symbol with the full compilation for attribute lookup.
        var combined = interfaceProvider.Combine(context.CompilationProvider);

        context.RegisterSourceOutput(combined, static (spc, pair) =>
        {
            var (interfaceSymbol, compilation) = pair;
            Execute(spc, interfaceSymbol, compilation);
        });
    }

    // ── Syntax predicate (no semantic model — very fast) ─────────────────────
    private static bool IsInterfaceWithHandlerAttributes(SyntaxNode node)
    {
        if (node is not InterfaceDeclarationSyntax iface) return false;
        foreach (var member in iface.Members)
        {
            if (member is not MethodDeclarationSyntax method) continue;
            foreach (var attrList in method.AttributeLists)
            foreach (var attr in attrList.Attributes)
            {
                var name = attr.Name.ToString();
                if (name is "CommandHandler" or "QueryHandler" or
                            "CommandHandlerAttribute" or "QueryHandlerAttribute")
                    return true;
            }
        }
        return false;
    }

    // ── Source production ─────────────────────────────────────────────────────
    private static void Execute(SourceProductionContext context, INamedTypeSymbol interfaceSymbol, Compilation compilation)
    {
        var handlerMethods = GetHandlerMethods(interfaceSymbol, compilation);
        if (handlerMethods.Count == 0) return;

        var source = GenerateHandlers(interfaceSymbol, handlerMethods, compilation);
        if (string.IsNullOrEmpty(source)) return;

        var fileName = $"{interfaceSymbol.ToDisplayString().Replace(".", "_").Replace("<", "_").Replace(">", "_")}_Handlers.g.cs";
        context.AddSource(fileName, SourceText.From(source, Encoding.UTF8));
    }

    private static List<IMethodSymbol> GetHandlerMethods(INamedTypeSymbol interfaceSymbol, Compilation compilation)
    {
        var handlerMethods = new List<IMethodSymbol>();

        var commandHandlerAttribute = compilation.GetTypeByMetadataName("Commandor.CommandHandlerAttribute");
        var queryHandlerAttribute = compilation.GetTypeByMetadataName("Commandor.QueryHandlerAttribute");

        if (commandHandlerAttribute == null && queryHandlerAttribute == null)
            return handlerMethods;

        foreach (var member in interfaceSymbol.GetMembers().OfType<IMethodSymbol>())
        {
            if (member.GetAttributes().Any(attr =>
                    SymbolEqualityComparer.Default.Equals(attr.AttributeClass, commandHandlerAttribute) ||
                    SymbolEqualityComparer.Default.Equals(attr.AttributeClass, queryHandlerAttribute)))
            {
                handlerMethods.Add(member);
            }
        }

        return handlerMethods;
    }

    private static string GenerateHandlers(INamedTypeSymbol interfaceSymbol, List<IMethodSymbol> handlerMethods, Compilation compilation)
    {
        var sb = new StringBuilder();
        var namespaceName = interfaceSymbol.ContainingNamespace.IsGlobalNamespace
            ? "Commandor"
            : interfaceSymbol.ContainingNamespace.ToDisplayString();
        var extensionMethods = new List<string>();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");

        foreach (var method in handlerMethods)
        {
            var handlerSource = GenerateHandler(interfaceSymbol, method, compilation, extensionMethods);
            if (!string.IsNullOrEmpty(handlerSource))
                sb.AppendLine(handlerSource);
        }

        // Emit a single public static extension class with all collected query extensions.
        if (extensionMethods.Count > 0)
        {
            var servicePrefix = GetServicePrefix(interfaceSymbol);
            sb.AppendLine($"    /// <summary>Auto-generated ICommandor query extensions for {interfaceSymbol.Name}.</summary>");
            sb.AppendLine($"    public static class Commandor{servicePrefix}Extensions");
            sb.AppendLine("    {");
            foreach (var ext in extensionMethods)
                sb.Append(ext);
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Returns true when <paramref name="type"/> implements IRequest (void) or IRequest&lt;T&gt; (with response).
    /// Used to distinguish IRequest-wrapped params from plain primitive/object params.
    /// </summary>
    private static bool ImplementsIRequest(ITypeSymbol type, Compilation compilation)
    {
        var iRequestGeneric = compilation.GetTypeByMetadataName("Commandor.IRequest`1");
        var iRequestVoid    = compilation.GetTypeByMetadataName("Commandor.IRequest");

        foreach (var iface in type.AllInterfaces)
        {
            if (iRequestGeneric != null && iface.IsGenericType &&
                SymbolEqualityComparer.Default.Equals(iface.OriginalDefinition, iRequestGeneric))
                return true;

            if (iRequestVoid != null && !iface.IsGenericType &&
                SymbolEqualityComparer.Default.Equals(iface, iRequestVoid))
                return true;
        }
        return false;
    }

    private static string Capitalize(string name)
        => name.Length == 0 ? name : char.ToUpperInvariant(name[0]) + name.Substring(1);

    /// <summary>
    /// Returns a prefix that uniquely identifies the service within its namespace.
    /// For nested interfaces (e.g. CachingTests.ITestService) the containing type name
    /// is prepended so that two different nested ITestService interfaces in the same
    /// namespace don't generate the same extension-class name.
    /// </summary>
    private static string GetServicePrefix(INamedTypeSymbol interfaceSymbol)
    {
        var name = interfaceSymbol.Name.TrimStart('I');
        return interfaceSymbol.ContainingType is { } ct ? ct.Name + name : name;
    }

    private static string GenerateHandler(
        INamedTypeSymbol interfaceSymbol,
        IMethodSymbol method,
        Compilation compilation,
        List<string> extensionMethods)
    {
        var returnType = method.ReturnType;
        if (returnType is not INamedTypeSymbol namedReturnType || namedReturnType.Name != "Task")
            return string.Empty;

        var responseType = namedReturnType.TypeArguments.Length > 0 ? namedReturnType.TypeArguments[0] : null;

        var queryAttribute = compilation.GetTypeByMetadataName("Commandor.QueryHandlerAttribute");
        var isQueryHandler = queryAttribute != null && method.GetAttributes()
            .Any(attr => SymbolEqualityComparer.Default.Equals(attr.AttributeClass, queryAttribute));

        // Read CacheTtlSeconds
        int cacheTtlSeconds = 0;
        if (isQueryHandler && queryAttribute != null)
        {
            var queryAttr = method.GetAttributes()
                .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, queryAttribute));
            var ttlArg = queryAttr?.NamedArguments.FirstOrDefault(n => n.Key == "CacheTtlSeconds");
            cacheTtlSeconds = ttlArg?.Value.Value is int ttl ? ttl : 0;
        }

        var format = new SymbolDisplayFormat(
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            miscellaneousOptions: SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier,
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included);

        var interfaceTypeName = interfaceSymbol.ToDisplayString(format);
        var responseTypeName = responseType?.ToDisplayString(format);
        var servicePrefix = GetServicePrefix(interfaceSymbol);

        // Collect all non-CancellationToken parameters.
        var ctType = compilation.GetTypeByMetadataName("System.Threading.CancellationToken");
        var plainParams = method.Parameters
            .Where(p => !SymbolEqualityComparer.Default.Equals(p.Type, ctType))
            .ToList();

        var hasCancellationTokenParam = method.Parameters
            .Any(p => SymbolEqualityComparer.Default.Equals(p.Type, ctType));

        if (plainParams.Count == 0)
        {
            if (!isQueryHandler || responseType == null || responseTypeName == null)
                return string.Empty;

            var noArgWrapperName = $"{method.Name}Request";
            var handlerNameNoArg = $"{servicePrefix}{method.Name}{noArgWrapperName}Handler";
            var serviceCall = hasCancellationTokenParam
                ? $"_service.{method.Name}(cancellationToken)"
                : $"_service.{method.Name}()";

            var sbNoArg = new StringBuilder();
            sbNoArg.AppendLine($"    /// <summary>Auto-generated request wrapper for parameterless query <c>{method.Name}</c>.</summary>");
            sbNoArg.AppendLine($"    internal sealed record {noArgWrapperName}() : global::Commandor.IRequest<{responseTypeName}>;");
            sbNoArg.AppendLine();

            sbNoArg.AppendLine("    [global::Commandor.GeneratedHandler]");
            sbNoArg.AppendLine($"    internal sealed class {handlerNameNoArg} : global::Commandor.IRequestHandler<{noArgWrapperName}, {responseTypeName}>");
            sbNoArg.AppendLine("    {");
            sbNoArg.AppendLine($"        private readonly {interfaceTypeName} _service;");
            sbNoArg.AppendLine("        private readonly global::Microsoft.Extensions.Caching.Memory.IMemoryCache _cache;");
            sbNoArg.AppendLine("        private readonly global::Commandor.CommandorContext _context;");
            sbNoArg.AppendLine();
            sbNoArg.AppendLine($"        public {handlerNameNoArg}({interfaceTypeName} service, global::Microsoft.Extensions.Caching.Memory.IMemoryCache cache, global::Commandor.CommandorContext context)");
            sbNoArg.AppendLine("        {");
            sbNoArg.AppendLine("            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));");
            sbNoArg.AppendLine("            _cache = cache ?? throw new global::System.ArgumentNullException(nameof(cache));");
            sbNoArg.AppendLine("            _context = context ?? throw new global::System.ArgumentNullException(nameof(context));");
            sbNoArg.AppendLine("        }");
            sbNoArg.AppendLine();
            sbNoArg.AppendLine($"        public async global::System.Threading.Tasks.Task<{responseTypeName}> HandleAsync({noArgWrapperName} request, global::System.Threading.CancellationToken cancellationToken = default)");
            sbNoArg.AppendLine("        {");
            sbNoArg.AppendLine($"            var cacheKey = global::Commandor.CacheKeyBuilder.Build(typeof({interfaceTypeName}), \"{method.Name}\", request);");
            sbNoArg.AppendLine($"            if (global::Microsoft.Extensions.Caching.Memory.CacheExtensions.TryGetValue<{responseTypeName}>(_cache, cacheKey, out var cachedValue))");
            sbNoArg.AppendLine("            {");
            sbNoArg.AppendLine("                return cachedValue!;");
            sbNoArg.AppendLine("            }");
            sbNoArg.AppendLine();
            sbNoArg.AppendLine($"            var result = await {serviceCall}.ConfigureAwait(false);");
            sbNoArg.AppendLine();
            sbNoArg.AppendLine("            var options = new global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions();");
            sbNoArg.AppendLine($"            global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryExtensions.AddExpirationToken(options, _context.GetToken(typeof({interfaceTypeName})));");
            if (cacheTtlSeconds > 0)
                sbNoArg.AppendLine($"            options.AbsoluteExpirationRelativeToNow = global::System.TimeSpan.FromSeconds({cacheTtlSeconds});");
            sbNoArg.AppendLine("            global::Microsoft.Extensions.Caching.Memory.CacheExtensions.Set(_cache, cacheKey, result, options);");
            sbNoArg.AppendLine();
            sbNoArg.AppendLine("            return result;");
            sbNoArg.AppendLine("        }");
            sbNoArg.AppendLine("    }");
            sbNoArg.AppendLine();

            var extNoArg = new StringBuilder();
            extNoArg.AppendLine($"        /// <summary>Queries <c>{interfaceSymbol.Name}.{method.Name}</c> with auto-generated caching. Supports parameterless query methods.</summary>");
            extNoArg.AppendLine($"        public static global::System.Threading.Tasks.Task<{responseTypeName}> {method.Name}(");
            extNoArg.AppendLine("            this global::Commandor.ICommandor commandor,");
            extNoArg.AppendLine("            global::System.Threading.CancellationToken cancellationToken = default)");
            extNoArg.AppendLine($"            => commandor.GetAsync(new {noArgWrapperName}(), cancellationToken);");
            extNoArg.AppendLine();
            extensionMethods.Add(extNoArg.ToString());

            return sbNoArg.ToString();
        }

        var firstParamType = plainParams[0].Type;
        var isIRequestMode = ImplementsIRequest(firstParamType, compilation);

        // ────────────────────────────────────────────────────────────────────
        // IRequest mode: first param already implements IRequest<T>.
        // Behaviour: identical to previous. Additionally, for QueryHandlers a
        // typed ICommandor extension method is generated:
        //   commandor.GetTodoByIdAsync(query)  →  commandor.GetAsync(query)
        // ────────────────────────────────────────────────────────────────────
        if (isIRequestMode)
        {
            var requestTypeName = firstParamType.ToDisplayString(format);
            var handlerName = $"{servicePrefix}{method.Name}{firstParamType.Name}Handler";
            var sb = new StringBuilder();

            if (responseType != null)
            {
                sb.AppendLine($"    [global::Commandor.GeneratedHandler]");
                sb.AppendLine($"    internal sealed class {handlerName} : global::Commandor.IRequestHandler<{requestTypeName}, {responseTypeName}>");
                sb.AppendLine("    {");
                sb.AppendLine($"        private readonly {interfaceTypeName} _service;");
                if (isQueryHandler)
                {
                    sb.AppendLine("        private readonly global::Microsoft.Extensions.Caching.Memory.IMemoryCache _cache;");
                    sb.AppendLine("        private readonly global::Commandor.CommandorContext _context;");
                }
                sb.AppendLine();
                var ctor = isQueryHandler
                    ? $"{interfaceTypeName} service, global::Microsoft.Extensions.Caching.Memory.IMemoryCache cache, global::Commandor.CommandorContext context"
                    : $"{interfaceTypeName} service";
                sb.AppendLine($"        public {handlerName}({ctor})");
                sb.AppendLine("        {");
                sb.AppendLine("            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));");
                if (isQueryHandler)
                {
                    sb.AppendLine("            _cache = cache ?? throw new global::System.ArgumentNullException(nameof(cache));");
                    sb.AppendLine("            _context = context ?? throw new global::System.ArgumentNullException(nameof(context));");
                }
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public async global::System.Threading.Tasks.Task<{responseTypeName}> HandleAsync({requestTypeName} request, global::System.Threading.CancellationToken cancellationToken = default)");
                sb.AppendLine("        {");
                if (isQueryHandler)
                {
                    sb.AppendLine($"            var cacheKey = global::Commandor.CacheKeyBuilder.Build(typeof({interfaceTypeName}), \"{method.Name}\", request);");
                    sb.AppendLine($"            if (global::Microsoft.Extensions.Caching.Memory.CacheExtensions.TryGetValue<{responseTypeName}>(_cache, cacheKey, out var cachedValue))");
                    sb.AppendLine("            {");
                    sb.AppendLine("                return cachedValue!;");
                    sb.AppendLine("            }");
                    sb.AppendLine();
                    sb.AppendLine($"            var result = await _service.{method.Name}(request, cancellationToken).ConfigureAwait(false);");
                    sb.AppendLine();
                    sb.AppendLine("            var options = new global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions();");
                    sb.AppendLine($"            global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryExtensions.AddExpirationToken(options, _context.GetToken(typeof({interfaceTypeName})));");
                    if (cacheTtlSeconds > 0)
                        sb.AppendLine($"            options.AbsoluteExpirationRelativeToNow = global::System.TimeSpan.FromSeconds({cacheTtlSeconds});");
                    sb.AppendLine("            global::Microsoft.Extensions.Caching.Memory.CacheExtensions.Set(_cache, cacheKey, result, options);");
                    sb.AppendLine();
                    sb.AppendLine("            return result;");
                }
                else
                {
                    sb.AppendLine($"            return await _service.{method.Name}(request, cancellationToken).ConfigureAwait(false);");
                }
                sb.AppendLine("        }");
                sb.AppendLine("    }");
            }
            else
            {
                sb.AppendLine($"    [global::Commandor.GeneratedHandler]");
                sb.AppendLine($"    internal sealed class {handlerName} : global::Commandor.IRequestHandler<{requestTypeName}>");
                sb.AppendLine("    {");
                sb.AppendLine($"        private readonly {interfaceTypeName} _service;");
                sb.AppendLine();
                sb.AppendLine($"        public {handlerName}({interfaceTypeName} service)");
                sb.AppendLine("        {");
                sb.AppendLine("            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        public async global::System.Threading.Tasks.Task HandleAsync({requestTypeName} request, global::System.Threading.CancellationToken cancellationToken = default)");
                sb.AppendLine("        {");
                sb.AppendLine($"            await _service.{method.Name}(request, cancellationToken).ConfigureAwait(false);");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
            }

            sb.AppendLine();

            // Extension method for QueryHandlers: commandor.MethodName(request) → commandor.GetAsync(request)
            if (isQueryHandler && responseType != null && responseTypeName != null)
            {
                var ext = new StringBuilder();
                ext.AppendLine($"        /// <summary>Sends <c>{firstParamType.Name}</c> and returns the cached result. Alias for <c>GetAsync</c>.</summary>");
                ext.AppendLine($"        public static global::System.Threading.Tasks.Task<{responseTypeName}> {method.Name}(");
                ext.AppendLine($"            this global::Commandor.ICommandor commandor,");
                ext.AppendLine($"            {requestTypeName} request,");
                ext.AppendLine($"            global::System.Threading.CancellationToken cancellationToken = default)");
                ext.AppendLine($"            => commandor.GetAsync(request, cancellationToken);");
                ext.AppendLine();
                extensionMethods.Add(ext.ToString());
            }

            return sb.ToString();
        }

        // ────────────────────────────────────────────────────────────────────
        // Plain-type mode: first param does NOT implement IRequest<T>.
        // Only supported for QueryHandlers (commands must own their request shape).
        //
        // The generator:
        //  1. Creates an internal wrapper record from all non-CT params.
        //  2. Creates the caching handler that unpacks the record and calls the service.
        //  3. Creates a public extension method so callers pass raw values:
        //       await commandor.GetTodoByIdAsync(id: 5)
        //     instead of:
        //       await commandor.GetAsync(new GetTodoByIdAsyncRequest(Id: 5))
        // ────────────────────────────────────────────────────────────────────
        if (!isQueryHandler || responseType == null || responseTypeName == null)
            return string.Empty; // CommandHandlers must use IRequest

        var wrapperName = $"{method.Name}Request";
        var wrapperFields = plainParams
            .Select(p => $"{p.Type.ToDisplayString(format)} {Capitalize(p.Name)}")
            .ToList();
        var wrapperFieldList = string.Join(", ", wrapperFields);
        var handlerNamePlain = $"{servicePrefix}{method.Name}{wrapperName}Handler";
        // The service is called with raw values unpacked from the wrapper record.
        var serviceCallArgs = string.Join(", ", plainParams.Select(p => $"request.{Capitalize(p.Name)}"));

        var sbp = new StringBuilder();

        sbp.AppendLine($"    /// <summary>Auto-generated request wrapper for plain-type query <c>{method.Name}</c>.</summary>");
        sbp.AppendLine($"    internal sealed record {wrapperName}({wrapperFieldList}) : global::Commandor.IRequest<{responseTypeName}>;");
        sbp.AppendLine();

        sbp.AppendLine($"    [global::Commandor.GeneratedHandler]");
        sbp.AppendLine($"    internal sealed class {handlerNamePlain} : global::Commandor.IRequestHandler<{wrapperName}, {responseTypeName}>");
        sbp.AppendLine("    {");
        sbp.AppendLine($"        private readonly {interfaceTypeName} _service;");
        sbp.AppendLine("        private readonly global::Microsoft.Extensions.Caching.Memory.IMemoryCache _cache;");
        sbp.AppendLine("        private readonly global::Commandor.CommandorContext _context;");
        sbp.AppendLine();
        sbp.AppendLine($"        public {handlerNamePlain}({interfaceTypeName} service, global::Microsoft.Extensions.Caching.Memory.IMemoryCache cache, global::Commandor.CommandorContext context)");
        sbp.AppendLine("        {");
        sbp.AppendLine("            _service = service ?? throw new global::System.ArgumentNullException(nameof(service));");
        sbp.AppendLine("            _cache = cache ?? throw new global::System.ArgumentNullException(nameof(cache));");
        sbp.AppendLine("            _context = context ?? throw new global::System.ArgumentNullException(nameof(context));");
        sbp.AppendLine("        }");
        sbp.AppendLine();
        sbp.AppendLine($"        public async global::System.Threading.Tasks.Task<{responseTypeName}> HandleAsync({wrapperName} request, global::System.Threading.CancellationToken cancellationToken = default)");
        sbp.AppendLine("        {");
        sbp.AppendLine($"            var cacheKey = global::Commandor.CacheKeyBuilder.Build(typeof({interfaceTypeName}), \"{method.Name}\", request);");
        sbp.AppendLine($"            if (global::Microsoft.Extensions.Caching.Memory.CacheExtensions.TryGetValue<{responseTypeName}>(_cache, cacheKey, out var cachedValue))");
        sbp.AppendLine("            {");
        sbp.AppendLine("                return cachedValue!;");
        sbp.AppendLine("            }");
        sbp.AppendLine();
        sbp.AppendLine($"            var result = await _service.{method.Name}({serviceCallArgs}, cancellationToken).ConfigureAwait(false);");
        sbp.AppendLine();
        sbp.AppendLine("            var options = new global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryOptions();");
        sbp.AppendLine($"            global::Microsoft.Extensions.Caching.Memory.MemoryCacheEntryExtensions.AddExpirationToken(options, _context.GetToken(typeof({interfaceTypeName})));");
        if (cacheTtlSeconds > 0)
            sbp.AppendLine($"            options.AbsoluteExpirationRelativeToNow = global::System.TimeSpan.FromSeconds({cacheTtlSeconds});");
        sbp.AppendLine("            global::Microsoft.Extensions.Caching.Memory.CacheExtensions.Set(_cache, cacheKey, result, options);");
        sbp.AppendLine();
        sbp.AppendLine("            return result;");
        sbp.AppendLine("        }");
        sbp.AppendLine("    }");
        sbp.AppendLine();

        // Extension method: exposes raw params so callers never touch the internal wrapper record.
        var extParamList = string.Join(", ", plainParams.Select(p => $"{p.Type.ToDisplayString(format)} {p.Name}"));
        var extCtorArgs  = string.Join(", ", plainParams.Select(p => $"{Capitalize(p.Name)}: {p.Name}"));
        var extp = new StringBuilder();
        extp.AppendLine($"        /// <summary>Queries <c>{interfaceSymbol.Name}.{method.Name}</c> with auto-generated caching. No IRequest wrapper needed.</summary>");
        extp.AppendLine($"        public static global::System.Threading.Tasks.Task<{responseTypeName}> {method.Name}(");
        extp.AppendLine($"            this global::Commandor.ICommandor commandor,");
        extp.AppendLine($"            {extParamList},");
        extp.AppendLine($"            global::System.Threading.CancellationToken cancellationToken = default)");
        extp.AppendLine($"            => commandor.GetAsync(new {wrapperName}({extCtorArgs}), cancellationToken);");
        extp.AppendLine();
        extensionMethods.Add(extp.ToString());

        return sbp.ToString();
    }
}
