namespace Commandor;

/// <summary>
/// Marks a class as auto-generated by the Commandor source generator.
/// Used for precise handler discovery during service registration instead of fragile name heuristics.
/// </summary>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
public sealed class GeneratedHandlerAttribute : Attribute { }
